services:
  - type: web
    name: backend-reservas
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: JWT_SECRET
        value: tu_secreto_super_seguro
      - key: STRIPE_SECRET_KEY
        value: tu_clave_secreta_stripe
      - key: MERCADOPAGO_ACCESS_TOKEN
        value: tu_token_mp
      - key: PAYPAL_CLIENT_ID
        value: tu_client_id_paypal
      - key: PAYPAL_CLIENT_SECRET
        value: tu_client_secret_paypal
      - key: PAYPAL_MODE
        value: sandbox

databases:
  - name: postgres-db
    plan: free
